export const AUTH_USER ='auth_user';
export const AUTH_ERROR = 'auth_error';
export const UNAUTH_USER = 'unauth_user';
export const FETCH_MESSAGE = 'fetch_message';
export const FETCH_USERINFO = 'fetch_userInfo';
export const FETCH_USERS = 'fetch_users';
export const CHANGE_PASSWORD = 'change_password';
export const CHANGE_AVATAR = 'change_avatar';
export const CHANGE_FOLLOWING ='change_following';
export const POST_CREATE = 'post_create';
export const FETCH_OWNPOSTINFO ='fetch_postInfo';
export const FETCH_FOLLOWINGPOSTINFO = 'fetch_followingPostInfo';
export const CHANGE_LIKES = 'change_likes';
export const POST_ERROR = 'post_error'
